Vagrant.configure(2) do |config|

  config.vm.synced_folder "../..", "/vagrant"
  config.vm.box = "mrlesmithjr/rhel-7"
  config.vm.box_version = "20160421.0"
  
  # Use the vagrant-cachier plugin, if installed, to cache downloaded packages
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.network "forwarded_port", guest: 3001, host: 3003
  config.vm.network "forwarded_port", guest: 3000, host: 9090
  config.vm.network "forwarded_port", guest: 8161, host: 8166

  config.vm.provider "virtualbox" do |vb|
   vb.gui = false
   vb.name = "oneops-rhel7"
   vb.memory = 6144
   vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
  end

  config.vm.provision :shell, path: "../../oo-prereqs.sh"
  config.vm.provision :shell, path: "../../oo-setup.sh", args: ENV["oo_validation_flag"]
end
